refactor: SVG 이미지 파일의 위치를 조정한다.
SilentBombers/click-me pull request #15
Opened 2023-10-11 14:33 UTC by Seungpang

## 작업 내용
+ SVG 이미지 파일의 위치와 크기를 조정
+ SVG 이미지 파일을 조작하는 역할은 SvgDocumentManipulator로 책임 위임
+ 이미지의 Random index를 가져오는 부분 EmojiRandomIndexGenerator util class로 분리

추가적인 리팩토링까지 추가하면 사이즈가 커져서 이 부분만 올립니다!

closed #14

2023-10-11 15:41 UTC, soominsohn requested changes
안녕하세요. 리팩토링 잘해주셨네요. 리뷰 몇개 남겼는데 확인해보시고 적용해주시면 감사하겠습니다. 🙇

2023-10-11 15:41 UTC, soominsohn commented on src/main/java/clickme/clickme/service/EmojiService.java
> +        return EMOJI_PATH + EmojiRandomIndexGenerator.getRandomNumber() + EMOJI_FORMAT;
책임분리 👍

2023-10-11 15:41 UTC, soominsohn commented on src/main/resources/static/images/emoji_0.svg
메롱은 Looks 안 Good To Me... 😢

2023-10-11 15:41 UTC, soominsohn commented on src/main/java/clickme/clickme/service/EmojiService.java
> +        svgDocumentManipulator.calculateSizeBasedOnCountLength(doc, count);
SvgDocumentManipulator를 이용해 `Document doc`을 조작하고 있군요!
전 이렇게 Object를 parameter로 넣어서 그 값을 조작해야하는 경우에는 return 값으로 조작된 Object를 받는편이에요.
예) 
```
Document textDrawnDocument = svgDocumentManipulator.drawText(doc, count);
Document sizeChangedDocument = svgDocumentManipulator.calculateSizeBasedOnCountLength(newDocument, count);
```
그렇게하면 `drawText `, `calculateSizeBasedOnCountLength`에서 parameter로 들어간 doc에 대해 어떠한 처리를 한다는 것이 명확해져요. 이렇게 하지않으면 parameter로 넣은 값만보고 어떤 일이 일어날지 알기 쉽지 않네용!

참고키워드: 부수효과, 순수함수
https://next-block.tistory.com/entry/Side-Effect-%EB%B6%80%EC%88%98%ED%9A%A8%EA%B3%BC
https://tsuel.tistory.com/56

2023-10-11 15:41 UTC, soominsohn commented on src/main/java/clickme/clickme/util/SvgDocumentManipulator.java
> +    public void drawText(Document doc, String count) {
이 부분에서 
`public Document drawText(Document doc, String count) {`
Document를 반환하면 좋을 것 같군요 "-"!

2023-10-11 15:41 UTC, soominsohn commented on src/main/java/clickme/clickme/util/SvgDocumentManipulator.java
> +    public void calculateSizeBasedOnCountLength(Document doc, String count) {
얘도 마찬가지 입니다!

2023-10-11 15:41 UTC, soominsohn commented on src/main/java/clickme/clickme/service/EmojiService.java
>          String count = getClickCount(id);
이전 PR들에서는 리뷰를 남기지 않았던 부분인데,
이제 슬슬 변하지 않을 변수와 파라미터에는 final을 붙여볼까요?
변하지않을 변수에는 final을 붙이면, 메서드 안에서 `이 변수는 변하지않겠구나!` 라고 파악하는게 쉬워질 것 같아요 😄

2023-10-12 14:45 UTC, Seungpang reviewed
수정할 부분 수정해서 반영했습니다! 😄

2023-10-12 14:45 UTC, Seungpang commented on src/main/java/clickme/clickme/service/EmojiService.java
>          String count = getClickCount(id);
저도 원래 final 키워드를 붙이는걸 선호하는데 노트북을 바꾸면서 intellij로 설정해서 사용하던게 풀려서 그냥 쓰고 있었네요!
앞으로 달아서 사용하겠습니다. 이번 pr에서는 변경분에만 일단 달고 다음 pr때 전체적으로 수정하겠습니다.

2023-10-12 14:45 UTC, Seungpang commented on src/main/java/clickme/clickme/service/EmojiService.java
> +        svgDocumentManipulator.calculateSizeBasedOnCountLength(doc, count);
음 말씀하신대로 어떠한 처리를 하는지가 불명확한거 같네요! 순수함수로 변경해봤습니다. 

```java
    public Document drawText(final Document doc, final String count) {
        Document copyDoc = (Document) doc.cloneNode(true);
        Element textElement = copyDoc.getElementById(TEXT_ELEMENT_ID);
        textElement.setTextContent(count);

        setAttribute(textElement, "font-size", "24");
        setAttribute(textElement, "font-family", "Arial, Helvetica, sans-serif");
        setAttribute(textElement, "font-weight", "bold");

        setAttribute(textElement, "x", TEXT_X_POSITION);
        setAttribute(textElement, "y", TEXT_Y_POSITION);

        return copyDoc;
    }
```
부수효과를 없애기 위해서 기존의 Document를 그대로 사용하는게 아니라 깊은 복사를 통해서 순수함수로 구현했습니다. 객체를 복사하여 작업하는 이유는 원본 객체의 상태를 보존해서 메서드 호출 전후로 원본 객체의 상태가 변하지 않으므로, 메서드의 동작을 더욱 명확하게 이해할 수 있습니다.

그리고 추가적인 `객체 생성으로 인한 비용이 추가적으로 발생해 성능에 영향을 끼치지 않을까?` 생각해봤지만 svg로 바꾸면서 메모리 사용량이 줄어들어서 그렇게 큰 무리가 아니라는 생각이 드네요

2023-10-12 14:45 UTC, Seungpang commented on src/main/resources/static/images/emoji_0.svg
이모지를 뭘 추가할지 골라야 할것같네요 ㅠㅠ

2023-10-12 15:27 UTC, soominsohn approved these changes
리뷰 반영 잘해주셨네요. 고맙습니다 👍 
머지할게용

2023-10-12 15:27 UTC, closed without merging