db에 저장된 사용자들의 github profile image를 가져오는 job을 추가한다.
SilentBombers/click-me pull request #40
Opened 2023-10-30 08:58 UTC by Seungpang

## 작업 내용
+ db에 create_at으로 당일에 추가된 유저의 github profile image를 찾아서 업데이트 하도록 job을 추가

## 이후에 추가할 내용
+ redis에서 mysql로 데이터를 동기화하는 작업도 당일 기준으로 동기화하도록 변경예정

closed #39

2023-10-31 14:11 UTC, soominsohn requested changes
안녕하세요! 구현하시느라 수고하셨어요.
리뷰 몇개 남겼는데 답변하시고 적용해주시면 고맙겠습니다.
파이팅~!

2023-10-31 14:11 UTC, soominsohn commented on transfer-service/src/main/java/clickme/transferservice/scheduler/TransferBatchScheduler.java
> +    @Scheduled(cron = "0 0 0 * * *")
이거 주기변경하신 이유가 따로 있나용?

2023-10-31 14:11 UTC, soominsohn commented on transfer-service/src/main/java/clickme/transferservice/service/GithubContributor.java
> +    private String avatar_url;
여기서 snake_case로 받으신 이유가 있을까용?
ObjectMapper로 받을 때 CamelCase로 받을지, snake_case로 받을지 설정할 수 있어요! 찾아보고 적용해볼까요? +_+

2023-10-31 14:11 UTC, soominsohn commented on transfer-service/src/main/java/clickme/transferservice/service/GithubApiService.java
> +    }
밑에 ObjectMapper 관련해서 리뷰단거에 더해서 !! 말씀드릴게요.
ObjectMapper 설정으로 다양한 일들을 할 수 있어요. 우리 코드에서 적용해 볼 수 있는 설정값이
- camel case로 설정.
- field 가 null일 경우 EmptyString으로 변환해서 받기. 
이 두가지가 있어 보이네요.

특히 두번째의 경우 GithubContributor의 `avatar_url`의 값을 사용하는 `MemberItemProcessor.process()`에서 null check를 하지 않아도 될 것 같아요. 어짜피 null이거나 empty string이면 기본 프로필이미지를 사용하니까요!
한번 알아보고 적용해볼까요? +_+

2023-10-31 14:27 UTC, Seungpang commented on transfer-service/src/main/java/clickme/transferservice/job/member/MemberItemProcessor.java
> +        return new ProfileUpdateMember(member.getNickname(), DEFAULT_AVATAR_URL.formatted(member.getNickname()));
자바 15부터 도입된 formatted메서드를 사용한 이유는 String.format보다는 더 직관적이고 가독성이 좋아보여서 사용하게 되었습니다!

2023-10-31 14:28 UTC, Seungpang commented on transfer-service/src/main/java/clickme/transferservice/job/member/UpdateMemberProfileImageJobConfig.java
> +                .pageSize(PAGE_SIZE)
멀고도 험한 배치의 세계..

2023-10-31 14:30 UTC, Seungpang commented on transfer-service/src/main/java/clickme/transferservice/scheduler/TransferBatchScheduler.java
> +    @Scheduled(cron = "0 0 0 * * *")
2시간 단위로 계속 업데이트를 하고 있는데 그렇게 자주 할 필요성을 느끼지 못했습니다. 그리고 github 프로필 이미지도 업데이트하면서 해당 시점을 언제로 잡을것인가를 생각해봤을때 0시를 기준으로 작업이 되어야 할 것 같아서 이렇게 변경했습니다.

2023-10-31 14:32 UTC, Seungpang commented on transfer-service/src/main/java/clickme/transferservice/service/GithubContributor.java
> +    private String avatar_url;
`@JsonProperty`를 사용하면 손쉽게 바꿀 수 있는데 일단 구현할때 최대한 간단하게 구현하다보니 넘기고 지나갔네요!

2023-11-01 11:12 UTC, soominsohn approved these changes
어푸합니당~!

2023-11-01 11:12 UTC, merged

2023-11-01 12:36 UTC, Seungpang commented on transfer-service/src/main/java/clickme/transferservice/service/GithubApiService.java
> +    }
ObjectMapper를 사용해서 설정값을 적용하려고 했는데 만약 다른 곳에서 null이 다른 의미를 가진다면 문제가 발생할 것 같아서
ObjectMapper의 설정을 하지 않고 일단은 최대한 간단하게 처리했습니다

MemberItemProcessor.process() 경우에도
```java
    @Override
    public ProfileUpdateMember process(final NicknameMember member) {
        String avatarUrl = Optional.ofNullable(githubApiService.getAvatarUrl(member.getNickname()))
                .filter(StringUtils::hasText)
                .orElse(DEFAULT_AVATAR_URL.formatted(member.getNickname()));

        return new ProfileUpdateMember(member.getNickname(), avatarUrl);
    }
```

위와 같은 형식으로 수정했습니다.