feat: redis에 저장된 click count db에 저장
SilentBombers/click-me pull request #8
Opened 2023-09-25 11:32 UTC by Seungpang

## 작업 내용
+ member 엔티티 생성
+ redis에만 저장된 데이터 mysql로 저장

## 고민한 내용
+ 클릭수가 올라갈 때마다 db에 저장한다면 db 리소스 낭비라고 생각
  + 10만건을 눌렀다고 10만건의 db 업데이트가 발생 (X)
  + 따라서 일정 주기 동안 스케줄링으로 업데이트 하는 방식을 취했습니다.

+ 스케줄링 부분에서 batchSize를 1000으로 지정한 이유 -> 한번에 많은 데이터를 메모리상으로 올린다면 자칫 OOM 이슈가 발생할 수 있습니다. 따라서 batchSize를 1000으로 정했습니다.
+ 현재는 스케줄링으로 처리하지만 나중에는 batch 서비스를 따로 분리하여 처리하도록 수정할 계획입니다.

closed #7

2023-09-25 11:39 UTC, soominsohn requested changes
안녕하세요 님아!
아주 잘 하셨네요. 리뷰 몇개 달았는데 확인 부탁드려요.

2023-09-25 11:39 UTC, soominsohn commented on src/main/java/clickme/clickme/domain/Member.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
롬복 Getter를 사용하셨군요! 자바17에는 record라는 자료형이 있는걸 아시나용? 
한번 적용해 볼까요?

2023-09-25 11:39 UTC, soominsohn commented on src/main/java/clickme/clickme/domain/Member.java
> +
updateClickCount 메서드를 보니 `DB 엑세스 객체인 Entity`에 비즈니스 로직이 들어있는 것 같아요. 
저는 데이터액세스 객체인 @Entity가 붙은 객체와, 도메인 객체를 따로 분리는 것을 추천해요!
사유: JPA와 Redis 둘다 씀.
지금 당장 적용하는 것보다는 천천히 다음 PR에 적용해볼까요? ~~

2023-09-25 11:39 UTC, soominsohn commented on src/main/java/clickme/clickme/service/DataTransferService.java
> +    @Transactional
지금은 한 WAS에 schedule이 돌고 있군요! 나중에 서버가 늘어나면 어떤일이 일어날까요?
또 어떻게 해결하면 좋을까요???

2023-09-25 11:39 UTC, soominsohn commented on src/main/java/clickme/clickme/service/DataTransferService.java
> +        int batchSize = 1000;
매직넘버로 빼보는건 어때요?

2023-09-25 11:39 UTC, soominsohn commented on src/main/java/clickme/clickme/service/DataTransferService.java
> +            }
중첩이 초큼,, 많네요,,
가독성을 위해 분리해보면 어떨까요? 👍✌️

2023-09-27 09:53 UTC, Seungpang reviewed
코멘트에 대한 답변 달아두었어요! 한번 확인하시고 의견 말씀해주세요

2023-09-27 09:53 UTC, Seungpang commented on src/main/java/clickme/clickme/service/DataTransferService.java
> +    @Transactional
스케일 아웃시 스케줄이 늘어난 서버만큼 발생하겠죠! 하지만 위에 언급한 대로 batch 서비스를 따로 분리하여 처리하면 이 부분이 자동적으로 해결될 것 같습니다!

2023-09-27 09:53 UTC, Seungpang commented on src/main/java/clickme/clickme/service/DataTransferService.java
> +        int batchSize = 1000;
batchSize를 상수로 빼는건 좋을 것 같네요! 다만 start = 0의 0은 매직넘버로 빼는 것 보다는 오히려 startIndex로 변수명을 바꿔서 의미를 더 명확하게 하겠습니다

2023-09-27 09:53 UTC, Seungpang commented on src/main/java/clickme/clickme/service/DataTransferService.java
> +            }
너무 무지성으로 코드를 짜버렸네요! 가독성 있게 수정했습니다!

2023-09-27 09:53 UTC, Seungpang commented on src/main/java/clickme/clickme/domain/Member.java
> +
JPA와 redis 둘다 사용한다고 했지만 실질적으로 redis에 저장하고 있는 데이터는 단순 String입니다. 따라서 Member 엔티티가 변경된다 하더라도 redis에는 영향이 없죠

entity와 도메인을 따로 분리해서 entity의 오염을 줄이고 데이터 액세스 객체와 도메인을 역할을 명확하게 하는 것은 좋지만 지금은 단순히 Member 하나만 사용하는 작은서비스여서 아직까지 분리할 필요성은 없어보여요

2023-09-27 12:48 UTC, soominsohn commented on src/main/java/clickme/clickme/domain/Member.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
그렇군요,,, 😓 
적절하지 않겠군요,,,
덕분에 새로운 것을 알게되었네요! 고마워요 👍

2023-09-27 12:56 UTC, merged